# This is a generated file. Not intended for manual editing.
services:
  app:
    build:
      context: "C:\\projects\\constant-learning\\ConstantLearning"
      dockerfile: "ConstantLearning/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net10.0/ConstantLearning.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "constantlearning:dev"
    ports: []
    volumes:
    - "C:\\projects\\constant-learning\\ConstantLearning\\ConstantLearning:/app:rw"
    - "C:\\projects\\constant-learning\\ConstantLearning:/src:rw"
    - "C:\\Users\\melni\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\melni\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
