apiVersion: v1
kind: Service
metadata:
  name: constant-learning
spec:
  selector:
    app: constant-learning
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
