apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
  - ../../base

images:
  - name: ghcr.io/GITHUB_USERNAME/constant-learning
    newName: ghcr.io/GITHUB_USERNAME/constant-learning
    newTag: SHA_REPLACED_BY_CICD

patchesStrategicMerge:
  - patch-env.yaml
